Nils cache
cecilianor/Qt-thesis pull request #63
Opened 2024-03-16 17:20 UTC by Didgy74

Unfinished atm.

Need to merge commits that are in main.

Need to comment code properly. Some comments may have been lost from previous code, will have to go over it.

2024-03-17 12:01 UTC, Didgy74 commented
Fixes have been made. Ready for review.

2024-03-17 14:29 UTC, cecilianor requested changes

2024-03-18 08:34 UTC, Didgy74 commented on lib/Utilities.h
> +namespace Bach {
This is not an issue, this is normal in C++.

2024-03-18 08:40 UTC, Didgy74 commented on lib/TileLoader.h
> +        const QString& basePath,
Right, this is just a helper function used by TileLoader AND the unit tests. The unit tests can use it to pre-load a tile-cache in a specific directory, and then be certain the TileLoader will read the cache correctly. It's used internally by TileLoader and from unit tests. The comments have been updated to reflect this.

2024-03-18 08:42 UTC, EimenOueslati approved these changes
Good!

2024-03-18 08:45 UTC, closed without merging